version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: GreenWeez raw data
    tables:
      - name: adwords
        identifier: raw_gz_adwords
      - name: bing
        identifier: raw_gz_bing
      - name: criteo
        identifier: raw_gz_criteo
      - name: facebook
        identifier: raw_gz_facebook